apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTDltblhuMTVHVTh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1EVXdPVFE0TXpaYUZ3MHpOREV4TURNd09UVXpNelphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURDWFE0UzJUQ1pqWEhSQ0xWQmFSSnJWeVczN2pOV3lhRnY5RDZyMjNqVGJHM2lHL1FId29UWWZrWHEKdjgyRTBoc2tJK1ZrcWxoVlZaTko0U1BScmJLTWw4eWgrRG9vdTRJaGhsd2VyU1grR3AwcVZlUGxrVjF3dFBmZAptRWR5aWlBTVI2Wnhwd0s5Z2ZLdVVqQUpTTHkxdXB5S0NXVEUxZG9FbGlQekUwVFRQRVFpWHdrYkJieGpSTEkrCm1QZEFDZy9VWlFrR2k0SjVTQm9FbWJTVzNHV2xtT25BUmRmK29hK2FjV2xpa1AyNUVqRStPNVVDaE1EVmMxeHIKZUVjY1ZLNkFpMWR6eGVpOUUzaUZTS2tFRmZtdDIzTEdTZFFCWFpNRnlWSEtlNHVCRzhWNnRDSlJMUDhpdHIxYwpOZk1zUnNoVkhsWEx6dERDNlNhcUQvSE5ld2xwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYml4MGt4NW5aZGpEOGtwQkVMNlN5UkJEMEdUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUYyNGtvblNaRgpvams5VVJuUzB4VGhwTjdna0RGZlpLT2twektqU2RqcFRkcDJ0ZnBaM2FDSWtoaFlLWWlhSytFSTc3ajFaZnV2CjFmZkEra09NYnVrYnBabHVWQThwdDg5dUVVT29VelYrbkFBU0E0RFZ6cFFQQk5ET0NWWktvMGZuYzkvTlQ5NkEKMnlZajE5Qmg4d1EyOWtnNElQSHM3TFpnQlMrbWcwUjg4T3E1WUxVNU9BWHZPWTZaMzJma3VsQVZPSDY1QmtTSgprYjR2RjhuZmpVVi9xMTVsaFhpb0tmNGR3VFRjK1VIdlhaVzhhNW8wcGI3Q09LRDZ6ZXVMNmFwNWQ2bnJpckVyCkYrM25YTjlKVTJYcjJVMTVoS0dIWGpsQXFCNnZIQS84RmlvUE1rTTFwUXFjZ1lmdTZpYmNSRkI1M3FFeFpEaFAKd1h3NUpzdVNOaVR3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://95429D39D2DD586BFFD6C057B392BEEF.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:211125444270:cluster/excalibur-eks-dev
- cluster:
    certificate-authority: /Users/venkataneha.avalur/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 16 Nov 2025 21:24:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:65361
  name: minikube
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:211125444270:cluster/excalibur-eks-dev
    namespace: neha
    user: arn:aws:eks:us-west-2:211125444270:cluster/excalibur-eks-dev
  name: arn:aws:eks:us-west-2:211125444270:cluster/excalibur-eks-dev
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 16 Nov 2025 21:24:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: arn:aws:eks:us-west-2:211125444270:cluster/excalibur-eks-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - excalibur-eks-dev
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: AdministratorAccess-211125444270
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: minikube
  user:
    client-certificate: /Users/venkataneha.avalur/.minikube/profiles/minikube/client.crt
    client-key: /Users/venkataneha.avalur/.minikube/profiles/minikube/client.key
